import type { ServiceCatalog } from '@/types/database';

export const initialServiceCatalog: ServiceCatalog[] = [
  {
    id: 'catalog-essencial',
    organization_id: 'org-arroba-local',
    name: 'Plano Essencial',
    description: null,
    default_price: 1500,
    recurrence: 'monthly',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'catalog-profissional',
    organization_id: 'org-arroba-local',
    name: 'Plano Profissional',
    description: null,
    default_price: 2500,
    recurrence: 'monthly',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'catalog-premium',
    organization_id: 'org-arroba-local',
    name: 'Plano Premium',
    description: null,
    default_price: 3500,
    recurrence: 'monthly',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'catalog-unidade',
    organization_id: 'org-arroba-local',
    name: 'Unidade adicional',
    description: null,
    default_price: 500,
    recurrence: 'monthly',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'catalog-biosprint',
    organization_id: 'org-arroba-local',
    name: 'Bio Sprint',
    description: null,
    default_price: 800,
    recurrence: 'one_off',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
