import type {
  Account,
  Contact,
  Opportunity,
  PipelineStage,
  ClientService,
  BillingCycle,
} from '@/types/database';

export type CommercialLead = {
  account: Account;
  contact: Contact;
  opportunity: Opportunity;
};

export type ClientWithServices = {
  account: Account;
  contact: Contact;
  services: ClientService[];
  billingCycles: BillingCycle[];
};

const organizationId = 'org-arroba-local';
const daviId = 'user-davi-local';
const richardsId = 'user-richards-local';
const now = new Date().toISOString();

export const pipelineStages: PipelineStage[] = [
  {
    id: 'stage-new',
    organization_id: organizationId,
    key: 'new_lead',
    name: 'Novo lead',
    position: 1,
    stage_group: 'open',
    color_token: 'brand',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-contact',
    organization_id: organizationId,
    key: 'contact_started',
    name: 'Contato iniciado',
    position: 2,
    stage_group: 'open',
    color_token: 'brand',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-meeting',
    organization_id: organizationId,
    key: 'meeting_scheduled',
    name: 'Reunião agendada',
    position: 3,
    stage_group: 'open',
    color_token: 'warning',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-diagnosis',
    organization_id: organizationId,
    key: 'diagnosis_done',
    name: 'Diagnóstico realizado',
    position: 4,
    stage_group: 'open',
    color_token: 'warning',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-proposal',
    organization_id: organizationId,
    key: 'proposal_sent',
    name: 'Proposta enviada',
    position: 5,
    stage_group: 'open',
    color_token: 'warning',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-negotiation',
    organization_id: organizationId,
    key: 'negotiation',
    name: 'Negociação',
    position: 6,
    stage_group: 'open',
    color_token: 'warning',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-won',
    organization_id: organizationId,
    key: 'won',
    name: 'Fechado ganho',
    position: 7,
    stage_group: 'won',
    color_token: 'success',
    is_active: true,
    created_at: now,
  },
  {
    id: 'stage-lost',
    organization_id: organizationId,
    key: 'lost',
    name: 'Fechado perdido',
    position: 8,
    stage_group: 'lost',
    color_token: 'neutral',
    is_active: true,
    created_at: now,
  },
];

export const initialClientServices: ClientService[] = [
  {
    id: 'cs-kianda-essencial',
    organization_id: organizationId,
    account_id: 'account-kianda',
    service_catalog_id: 'catalog-essencial',
    status: 'active',
    contracted_price: 1500,
    recurrence: 'monthly',
    billing_day: 5,
    valid_until: null,
    created_at: now,
    updated_at: now,
    closed_at: null,
  },
  {
    id: 'cs-kianda-unidade',
    organization_id: organizationId,
    account_id: 'account-kianda',
    service_catalog_id: 'catalog-unidade',
    status: 'active',
    contracted_price: 500,
    recurrence: 'monthly',
    billing_day: 5,
    valid_until: null,
    created_at: now,
    updated_at: now,
    closed_at: null,
  },
  {
    id: 'cs-bio-biosprint',
    organization_id: organizationId,
    account_id: 'account-bio',
    service_catalog_id: 'catalog-biosprint',
    status: 'active',
    contracted_price: 800,
    recurrence: 'one_off',
    billing_day: null,
    valid_until: null,
    created_at: now,
    updated_at: now,
    closed_at: null,
  },
];

export const initialBillingCycles: BillingCycle[] = [
  {
    id: 'bc-kianda-essencial-jul',
    organization_id: organizationId,
    account_id: 'account-kianda',
    client_service_id: 'cs-kianda-essencial',
    reference_month: '2026-07-01',
    amount: 1500,
    status: 'paid',
    due_date: '2026-07-05',
    paid_at: '2026-07-03T10:00:00.000Z',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'bc-kianda-essencial-ago',
    organization_id: organizationId,
    account_id: 'account-kianda',
    client_service_id: 'cs-kianda-essencial',
    reference_month: '2026-08-01',
    amount: 1500,
    status: 'pending',
    due_date: '2026-08-05',
    paid_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'bc-kianda-unidade-jul',
    organization_id: organizationId,
    account_id: 'account-kianda',
    client_service_id: 'cs-kianda-unidade',
    reference_month: '2026-07-01',
    amount: 500,
    status: 'late',
    due_date: '2026-07-05',
    paid_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'bc-bio-biosprint',
    organization_id: organizationId,
    account_id: 'account-bio',
    client_service_id: 'cs-bio-biosprint',
    reference_month: '2026-07-01',
    amount: 800,
    status: 'pending',
    due_date: '2026-07-10',
    paid_at: null,
    created_at: now,
    updated_at: now,
  },
];

export const initialCommercialLeads: CommercialLead[] = [
  {
    account: {
      id: 'account-kianda',
      organization_id: organizationId,
      lifecycle_status: 'client',
      status: 'active',
      display_name: 'Kianda Calçados',
      legal_name: null,
      cnpj: null,
      segment: 'Varejo de moda',
      city: 'Aracruz',
      state: 'ES',
      address: null,
      instagram_url: 'https://instagram.com/kiandacalcados',
      website_url: null,
      lead_temperature: 'hot',
      lead_source: 'Indicação',
      owner_id: daviId,
      strategic_notes: 'Rede local com múltiplas unidades e potencial de plano profissional.',
      created_by: daviId,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    contact: {
      id: 'contact-kianda',
      organization_id: organizationId,
      account_id: 'account-kianda',
      full_name: 'Marina',
      role_title: 'Sócia',
      phone: null,
      whatsapp: '(27) 99999-0001',
      email: 'marina@kianda.local',
      is_primary: true,
      notes: null,
      created_at: now,
      updated_at: now,
    },
    opportunity: {
      id: 'opp-kianda',
      organization_id: organizationId,
      account_id: 'account-kianda',
      primary_contact_id: 'contact-kianda',
      pipeline_stage_id: 'stage-won',
      title: 'Plano Profissional + unidade adicional',
      estimated_value: 2000,
      expected_close_date: '2026-06-30',
      proposal_valid_until: '2026-07-05',
      owner_id: daviId,
      next_follow_up_at: null,
      lost_reason: null,
      won_at: '2026-06-28T14:30:00.000Z',
      lost_at: null,
      converted_at: '2026-07-01T09:00:00.000Z',
      created_at: now,
      updated_at: now,
    },
  },
  {
    account: {
      id: 'account-bio',
      organization_id: organizationId,
      lifecycle_status: 'lead',
      status: 'active',
      display_name: 'Studio BioForma',
      legal_name: null,
      cnpj: null,
      segment: 'Saúde e estética',
      city: 'Linhares',
      state: 'ES',
      address: null,
      instagram_url: null,
      website_url: null,
      lead_temperature: 'warm',
      lead_source: 'Instagram',
      owner_id: richardsId,
      strategic_notes: 'Interesse inicial em Bio Sprint e identidade visual.',
      created_by: richardsId,
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    contact: {
      id: 'contact-bio',
      organization_id: organizationId,
      account_id: 'account-bio',
      full_name: 'Camila',
      role_title: 'Proprietária',
      phone: null,
      whatsapp: '(27) 99999-0002',
      email: null,
      is_primary: true,
      notes: null,
      created_at: now,
      updated_at: now,
    },
    opportunity: {
      id: 'opp-bio',
      organization_id: organizationId,
      account_id: 'account-bio',
      primary_contact_id: 'contact-bio',
      pipeline_stage_id: 'stage-meeting',
      title: 'Bio Sprint',
      estimated_value: 350,
      expected_close_date: '2026-07-15',
      proposal_valid_until: null,
      owner_id: richardsId,
      next_follow_up_at: '2026-07-10T16:00:00.000Z',
      lost_reason: null,
      won_at: null,
      lost_at: null,
      converted_at: null,
      created_at: now,
      updated_at: now,
    },
  },
];
